TIMEFRAME = "5m"
DEFAULT_BALANCE = 1000
DEFAULT_RISK = 1.5

TOP_COINS = ["BTC/USDT","ETH/USDT","SOL/USDT","BNB/USDT","XRP/USDT","DOGE/USDT","AVAX/USDT","ADA/USDT","LINK/USDT","MATIC/USDT"]

USERS = {
    "admin": "12345",
    "mahfuj": "ai123"
}
